#!/bin/bash
# Find file conflict files generated by Syncthing in a given path

if [ "$2" == "-r" ]; then
    find "$1" -name '*sync-conflict*' -exec rm -fv {} \;
else
    find "$1" -name '*sync-conflict*'
fi
